"""
Analyze position control log generated by ESP32.

Expected format (CSV):
t_ms,ref_pos,y_pos,y_vel,e_pos,e_vel,x1_hat,x2_hat,u,delta_cnt,cnt_raw,cnt_rel

Usage:
    python analyze_control_log.py output.txt
"""

from __future__ import annotations

import sys
from pathlib import Path
from io import StringIO

import pandas as pd
import matplotlib.pyplot as plt


def load_clean_data(file_path: str) -> pd.DataFrame:
    """
    Reads the log file and keeps only valid CSV lines.
    Removes boot logs, warnings, and any noise.
    """
    path = Path(file_path)

    if not path.exists():
        raise FileNotFoundError(f"File not found: {path}")

    valid_lines: list[str] = []

    with path.open("r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            text = line.strip()

            if not text:
                continue

            # Keep header
            if text.startswith("t_ms,ref_pos,"):
                valid_lines.append(text)
                continue

            # Keep only numeric lines (actual data)
            if text[0].isdigit():
                valid_lines.append(text)

    if not valid_lines:
        raise ValueError("No valid CSV data found in file.")

    clean_content = "\n".join(valid_lines)
    df = pd.read_csv(StringIO(clean_content))

    return df


def prepare_time_axis(df: pd.DataFrame) -> pd.DataFrame:
    """
    Converts time from ms to seconds and normalizes start at t=0.
    """
    df = df.copy()

    df["time_s"] = df["t_ms"] / 1000.0
    df["time_s"] -= df["time_s"].iloc[0]

    return df


def print_summary(df: pd.DataFrame) -> None:
    """
    Prints a quick summary of system behavior.
    """
    print("\n=== Experiment Summary ===")
    print(f"Samples: {len(df)}")
    print(f"Total time: {df['time_s'].iloc[-1]:.3f} s")

    print(f"Final reference: {df['ref_pos'].iloc[-1]:.4f} rad")
    print(f"Final position: {df['y_pos'].iloc[-1]:.4f} rad")
    print(f"Final error: {df['e_pos'].iloc[-1]:.4f} rad")

    print(f"Max control effort: {df['u'].abs().max():.4f}")
    print(f"Max velocity: {df['y_vel'].abs().max():.4f} rad/s")


def plot_position(df: pd.DataFrame) -> None:
    """
    Plot reference vs real vs estimated position.
    """
    plt.figure(figsize=(10, 5))
    plt.plot(df["time_s"], df["ref_pos"], label="Reference")
    plt.plot(df["time_s"], df["y_pos"], label="Real Position")
    plt.plot(df["time_s"], df["x1_hat"], label="Estimated Position")

    plt.title("Position Comparison")
    plt.xlabel("Time [s]")
    plt.ylabel("Position [rad]")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()


def plot_velocity(df: pd.DataFrame) -> None:
    """
    Plot real vs estimated velocity.
    """
    plt.figure(figsize=(10, 5))
    plt.plot(df["time_s"], df["y_vel"], label="Real Velocity")
    plt.plot(df["time_s"], df["x2_hat"], label="Estimated Velocity")

    plt.title("Velocity Comparison")
    plt.xlabel("Time [s]")
    plt.ylabel("Velocity [rad/s]")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()


def plot_error(df: pd.DataFrame) -> None:
    """
    Plot position and velocity error.
    """
    plt.figure(figsize=(10, 5))
    plt.plot(df["time_s"], df["e_pos"], label="Position Error")
    plt.plot(df["time_s"], df["e_vel"], label="Velocity Error")

    plt.title("System Errors")
    plt.xlabel("Time [s]")
    plt.ylabel("Error")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()


def plot_control(df: pd.DataFrame) -> None:
    """
    Plot control signal.
    """
    plt.figure(figsize=(10, 5))
    plt.plot(df["time_s"], df["u"], label="Control Input")

    plt.title("Control Signal")
    plt.xlabel("Time [s]")
    plt.ylabel("Control [-1, 1]")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()


def plot_encoder(df: pd.DataFrame) -> None:
    """
    Plot encoder data.
    """
    plt.figure(figsize=(10, 5))
    plt.plot(df["time_s"], df["cnt_raw"], label="Raw Count")
    plt.plot(df["time_s"], df["cnt_rel"], label="Relative Count")
    plt.plot(df["time_s"], df["delta_cnt"], label="Delta Count")

    plt.title("Encoder Signals")
    plt.xlabel("Time [s]")
    plt.ylabel("Counts")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()


def save_clean_data(df: pd.DataFrame, output_file: str = "clean_data.csv") -> None:
    """
    Save cleaned dataset for further analysis.
    """
    df.to_csv(output_file, index=False)
    print(f"\nClean data saved to: {output_file}")


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage:")
        print("    python analyze_control_log.py output.txt")
        sys.exit(1)

    file_path = sys.argv[1]

    df = load_clean_data(file_path)
    df = prepare_time_axis(df)

    print_summary(df)
    save_clean_data(df)

    plot_position(df)
    plot_velocity(df)
    plot_error(df)
    plot_control(df)
    plot_encoder(df)

    plt.show()


if __name__ == "__main__":
    main()